trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: 'Package'
  displayName: 'Package the helm chart'
  jobs:
   - job: PackageHelmChart
     steps:
       - task: HelmInstaller@1
         displayName: 'Install Helm'
         inputs:
           helmVersionToInstall: 'latest'

       - task: HelmDeploy@0
         displayName: 'create helm package for simpleweb'
         inputs:
           command: 'package'
           chartPath: charts/simpleweb
           destination: $(Build.ArtifactStagingDirectory)
           updateDependency: true
           save: false

       - task: PublishBuildArtifacts@1
         displayName: 'publish simpleweb helm package for simpleweb as a pipeline artifact'
         inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
- stage: 'DeployRing0'
  displayName: 'Deploy simpleweb and simpleapi to Ring 0'
  jobs:
    - job: DeployHelmPackage
      steps:
        - task: DownloadBuildArtifacts@0
          displayName: Download the latest helm package
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'
        - task: HelmInstaller@1
          displayName: Install Helm 
          inputs:
            helmVersionToInstall: 3.1.2
        - task: HelmDeploy@0
          displayName: Deploy simpleweb helm package to Ring 0 aks namespace
          inputs:
            azureSubscription: cicdsubscription
            azureResourceGroup: iliasj-aksworkshop
            kubernetesCluster: iliasjaks
            namespace: simpleweb-ring0
            chartPath: $(Agent.BuildDirectory)\*.tgz
- stage: 'DeployRing1'
  displayName: 'Deploy simpleweb and simpleapi to Ring 1'
  jobs:
  - job: DeployHelmPackage
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Download the latest helm package
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop'
          downloadPath: '$(System.ArtifactsDirectory)'
      - task: HelmInstaller@1
        displayName: Install Helm 
        inputs:
          helmVersionToInstall: 3.1.2
      - task: HelmDeploy@0
        displayName: Deploy simpleweb helm package to Ring 0 aks namespace
        inputs:
          azureSubscription: cicdsubscription
          azureResourceGroup: iliasj-aksworkshop
          kubernetesCluster: iliasjaks
          namespace: simpleweb-ring1
          chartPath: $(Agent.BuildDirectory)\*.tgz
          